name: Deploy Backend to AWS ECS

on:
  push:
    branches:
      - main # O la rama que uses para despliegues

env:
  [cite_start]AWS_REGION: us-west-1 # Tu región: Norte de California [cite: 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
  [cite_start]ECR_REPOSITORY: simple-backend-api # Nombre de tu repositorio ECR [cite: 10]
  [cite_start]ECS_SERVICE: simple-backend-api-service-Ana-Belen # Nombre de tu servicio ECS [cite: 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
  [cite_start]ECS_CLUSTER: simple-backend-cluster-Ana-Belen # Nombre de tu clúster ECS [cite: 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
  [cite_start]ECS_TASK_DEFINITION: simple-backend-api-task-definition-Ana-Belen # Nombre de tu familia de definición de tarea [cite: 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
  [cite_start]CONTAINER_NAME: simple-backend-api-container # Nombre de tu contenedor en la definición de tarea [cite: 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write # Necesario para OpenID Connect (OIDC)
      contents: read
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        [cite_start]role-to-assume: arn:aws:iam::577644414877:role/GitHubActionsECSRole-AnaBelen # Tu ID de cuenta AWS y nombre del rol [cite: 13]
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build, tag, and push image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: latest
      run: |
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

    - name: Download task definition
      run: |
        aws ecs describe-task-definition --task-definition ${{ env.ECS_TASK_DEFINITION }} --query taskDefinition > task-definition.json

    - name: Fill in the new image ID in the Amazon ECS task definition
      id: task-def
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: task-definition.json
        container-name: ${{ env.CONTAINER_NAME }}
        image: ${{ steps.build-image.outputs.image }}

    - name: Deploy Amazon ECS task definition
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: ${{ steps.task-def.outputs.task-definition }}
        service: ${{ env.ECS_SERVICE }}
        cluster: ${{ env.ECS_CLUSTER }}
        wait-for-service-stability: true